package ca.uvic.seng330.assn3;

public enum Command {
  LIGHTBULB_TOGGLE,
  LIGHTBULB_GET_CONDITION,
  LIGHTBULB_CONDITION_CHANGED,
  THERMOSTAT_TOGGLE,
  THERMOSTAT_GET_CONDITION,
  THERMOSTAT_SET_TEMP,
  THERMOSTAT_GET_TEMP,
  THERMOSTAT_SET_UNIT,
  THERMOSTAT_GET_UNIT,
  SMARTPLUG_TOGGLE,
  SMARTPLUG_GET_CONDITION,
  CAMERA_GET_CONDITION,
  CAMERA_TOGGLE,
  CAMERA_IS_RECORDING,
  CAMERA_RECORD,
  CAMERA_STOP_RECORD,
  HUB_GET_CONDITION,
  HUB_TOGGLE_POWER
}
