package ca.uvic.seng330.assn3;

public enum Command {
  LIGHTBULB_TOGGLE,
  LIGHTBULB_GET_CONDITION,
  THERMOSTAT_SET_TEMP,
  THERMOSTAT_GET_TEMP,
  THERMOSTAT_SET_UNIT,
  THERMOSTAT_GET_UNIT,
  SMARTPLUG_TOGGLE,
  SMARTPLUG_GET_CONDITION
}
